language: python
sudo: false
cache:
  - pip

before_install:
  - set -e

install:
  - pip install --upgrade pip
  - pip install --upgrade --pre -r requirements.txt
  - pip install --upgrade --pre -r test_requirements.txt

script:
  - pytest --cov=samlauthenticator --cov-report term-missing

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
  allow_failures:
    - python: nightly
